import type { ReactNode } from "react";
import { Handle, Position } from "@xyflow/react";
import type { CanvasNodeData } from "@/types/canvas";
import { NODE_CONFIG } from "@/constants/nodes-config";
import { StatusDot } from "@/components/ui/status-dot";
import { cn } from "@/lib/utils";

const BaseNodeWrapper = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <div
    className={cn(
      "w-55 rounded-xl border bg-surface px-4 py-3 shadow-sm",
      className
    )}
  >
    {children}
  </div>
);

const BaseNodeEyebrow = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <div
    className={cn(
      "mb-1.5 flex items-center gap-1.5 font-mono text-xs uppercase tracking-widest",
      className
    )}
  >
    {children}
  </div>
);

const BaseNodeTitle = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <h3
    className={cn(
      "mb-1 text-md font-semibold leading-snug tracking-tight text-foreground",
      className
    )}
  >
    {children}
  </h3>
);

const BaseNodeText = ({
  children,
  className,
}: {
  children: ReactNode | ReactNode[];
  className?: string;
}) => (
  <p className={cn("text-sm leading-snug text-muted", className)}>{children}</p>
);

const BaseNodeFooter = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <footer
    className={cn(
      "mt-2 border-t border-border pt-1.5 font-mono text-xs text-dim",
      className
    )}
  >
    {children}
  </footer>
);

type BaseNodeProps = {
  data: CanvasNodeData;
  children: ReactNode;
  className?: string;
};

const BaseNode = ({ data, children, className }: BaseNodeProps) => {
  const config = NODE_CONFIG[data.variant];

  return (
    <BaseNodeWrapper className={cn(config.borderClass, className)}>
      <Handle
        type="target"
        position={Position.Left}
        className="h-2! w-2! border-border-bright! bg-dim!"
      />

      <BaseNodeEyebrow className={config.colorClass}>
        <StatusDot className={config.dotColor} />
        {config.label}
      </BaseNodeEyebrow>

      <BaseNodeTitle>{data.title}</BaseNodeTitle>

      {children}

      <BaseNodeFooter>
        {data.source === "agent" ? "Generated by agent" : "Edited by user"}
      </BaseNodeFooter>

      <Handle
        type="source"
        position={Position.Right}
        className="h-2! w-2! border-border-bright! bg-dim!"
      />
    </BaseNodeWrapper>
  );
};

export {
  BaseNode,
  BaseNodeEyebrow,
  BaseNodeTitle,
  BaseNodeText,
  BaseNodeFooter,
};
