import type { ReactNode } from "react";
import { Handle, Position } from "@xyflow/react";
import type { CanvasNodeData } from "@/types/canvas";
import { NODE_CONFIG } from "@/constants/nodes-config";
import { StatusDot } from "@/components/ui/status-dot";

type BaseNodeProps = {
  data: CanvasNodeData;
  children: ReactNode;
};

const BaseNode = ({ data, children }: BaseNodeProps) => {
  const config = NODE_CONFIG[data.variant];

  return (
    <div
      className={`w-55 rounded-xl border bg-surface px-4 py-3 shadow-sm ${config.borderClass}`}
    >
      <Handle
        type="target"
        position={Position.Left}
        className="h-2! w-2! border-border-bright! bg-dim!"
      />

      <div
        className={`mb-1.5 flex items-center gap-1.5 font-mono text-xs uppercase tracking-widest ${config.colorClass}`}
      >
        <StatusDot className={config.dotColor} />
        {config.label}
      </div>

      <h3 className="mb-1 text-md font-semibold leading-snug tracking-tight text-foreground">
        {data.title}
      </h3>

      {children}

      <footer className="mt-2 border-t border-border pt-1.5 font-mono text-xs text-dim">
        {data.source === "agent" ? "Generated by agent" : "Edited by user"}
      </footer>

      <Handle
        type="source"
        position={Position.Right}
        className="h-2! w-2! border-border-bright! bg-dim!"
      />
    </div>
  );
};

export { BaseNode };
