import type { ReactNode } from "react";
import { Handle, Position } from "@xyflow/react";
import type { CanvasNodeData, NodeConfig } from "@/types/canvas";
import { NODE_CONFIG } from "@/constants/nodes-config";
import { cn } from "@/lib/utils";
import { useCanvasState } from "@/contexts/canvas-state-context";
import { StatusDot } from "@/components/ui/status-dot";

type BaseNodeWrapperProps = {
  children: ReactNode;
  selected?: boolean;
  config: NodeConfig;
  className?: string;
};

const BaseNodeWrapper = ({
  children,
  selected,
  config,
  className,
}: BaseNodeWrapperProps) => (
  <div
    className={cn(
      "relative w-60 rounded-lg bg-surface",
      selected
        ? cn("border-2", config.selectedBorderClass, config.selectedShadowClass)
        : "border border-border shadow-md",
      className
    )}
  >
    {selected && (
      <StatusDot
        className={cn("absolute right-2 top-2 z-50", config.selectedDotClass)}
      />
    )}
    {children}
  </div>
);

const BaseNodeHeader = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <div className={cn("px-4 pt-3 mb-3 border-b border-border", className)}>
    {children}
  </div>
);

const BaseNodeContent = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <div className={cn("px-4 my-3 space-y-3 max-w-min min-w-60", className)}>
    {children}
  </div>
);

const BaseNodeFooter = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <div className={cn("px-4 pb-3 pt-1.5 border-t border-border", className)}>
    {children}
  </div>
);

const BaseNodeEyebrow = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <div
    className={cn(
      "mb-1.5 flex items-center gap-1.5 font-mono text-[10px] uppercase font-medium",
      className
    )}
  >
    {children}
  </div>
);

const BaseNodeTitle = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <h3
    className={cn(
      "text-lg font-medium leading-tight text-foreground",
      className
    )}
  >
    {children}
  </h3>
);

const BaseNodeSubtitle = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <h4
    className={cn(
      "text-sm font-medium leading-tight text-foreground",
      className
    )}
  >
    {children}
  </h4>
);

const BaseNodeText = ({
  children,
  className,
}: {
  children: ReactNode | ReactNode[];
  className?: string;
}) => (
  <p className={cn("text-xs leading-snug text-muted", className)}>{children}</p>
);

const BaseNodeDetails = ({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) => (
  <p className={cn("font-mono text-[10px] text-dim", className)}>{children}</p>
);

type BaseNodeProps = {
  id: string;
  data: CanvasNodeData;
  children: ReactNode;
  className?: string;
};

const BaseNode = ({ data, children, className, id }: BaseNodeProps) => {
  const { selectedNodeId } = useCanvasState();
  const config = NODE_CONFIG[data.variant];
  const Icon = config.icon;

  return (
    <BaseNodeWrapper
      selected={selectedNodeId === id}
      config={config}
      className={className}
    >
      <Handle
        type="target"
        position={Position.Left}
        className="h-2! w-2! border-border! bg-dim!"
      />

      <BaseNodeHeader>
        <BaseNodeEyebrow className={config.textColorClass}>
          <Icon width={16} height={16} aria-hidden="true" />
          {config.label}
        </BaseNodeEyebrow>
      </BaseNodeHeader>

      <BaseNodeContent>
        <BaseNodeTitle>{data.title}</BaseNodeTitle>
        {children}
      </BaseNodeContent>

      <BaseNodeFooter>
        <BaseNodeDetails>
          {data.source === "agent"
            ? "Generated by Insight Copilot"
            : "Edited by user"}
        </BaseNodeDetails>
      </BaseNodeFooter>

      <Handle
        type="source"
        position={Position.Right}
        className="h-2! w-2! border-border! bg-dim!"
      />
    </BaseNodeWrapper>
  );
};

export {
  BaseNode,
  BaseNodeSubtitle,
  BaseNodeDetails,
  BaseNodeEyebrow,
  BaseNodeTitle,
  BaseNodeText,
  BaseNodeFooter,
};
